### ISSUE TITLE
Question: Other language can't use?

### ISSUE THREAD

**Issue by Daki404** [ajndkr/lanarky#107]
First of all, thank you for making this repo.
This is really convenient!

But, lanarky can't use Korean...
OPENAI_API(GPT api) can use Korean, Why lanarky can't use?

I'm trying to find something prompt_template, I can't find.
Can I get some advice?

**Comment by ajndkr** [comment]
@Daki404 can you please elaborate on the issue? this repo only helps in exposing langchain applications as a FastAPI endpoint. It doesn't control the LLM calls.
