### ISSUE TITLE
Question: SSE StreamingResponse support for FastAPI

### ISSUE THREAD

**Issue by imraminradmand** [ajndkr/lanarky#112]
As a user, I want to send a request to a FastAPI endpoint and have the response from the LLM be streamed directly to the frontend. The follow goes as such:

- User makes post request to the endpoint
- backend does some processing, and calls the LLM
- The response from the LLM is directly streamed to the user in the frontend via StreamingResponse.

I'm currently taking the response from the LLM, chunking and then streaming it but this is slow, and I need to speed it up.

I'm very new to using Lanarky, and haven't been able to make this work with the current available api docs. If this is an available feature I would appreciate any guidance on how to achieve this.

**Comment by ajndkr** [comment]
@imraminradmand have you maybe looked into the examples? you can check out the conversational chain example: https://github.com/ajndkr/lanarky/blob/main/examples/app/conversation_chain.py

2 points to notice:

```
def create_chain():
    return ConversationChain(
        llm=ChatOpenAI(
            temperature=0,
            streaming=True,
        ),
        verbose=True,
    )
```

you need to set `streaming=True` for the LLM call (in this case it's `ChatOpenAI` maybe you have something else?)

```
langchain_router = LangchainRouter(
    langchain_url="/chat", langchain_object=chain, streaming_mode=1
)
```

you need to pass `streaming_mode=1` when intialising the `LangchainRouter`. Let me know if this helps.
