### ISSUE TITLE
Final answer not returned with using GPTCache, with streaming JSON.

### ISSUE THREAD

**Issue by auxon** [ajndkr/lanarky#113]
EDIT:  My source code example is available here:  https://github.com/ajndkr/lanarky/discussions/108#discussion-5501534

I am using GPTCache but it doesn't return the retrieved answer, although I can see the answer in Langsmith and my terminal output (with langchain.debug=True and lanchain.verbose=True).  I get back a response like:

```
{"token":"","source_documents":[{"page_content":"without some hints touching the plain facts, historical and otherwise, of the fishery, they might scout at Moby Dick as a monstrous fable, or still worse and more detestable, a hideous and intolerable allegory.","metadata":{"source":"/Users/rah/titleDownloads/2c169b4c-8e8d-4dd4-8b57-82d5a21e4a1b/fae7a981-6f18-423d-b8e1-a7b0c73101fc.html"}},{"page_content":"without some hints touching the plain facts, historical and otherwise, of the fishery, they might scout at Moby Dick as a monstrous fable, or still worse and more detestable, a hideous and intolerable allegory.","metadata":{"source":"/Users/rah/titleDownloads/2c169b4c-8e8d-4dd4-8b57-82d5a21e4a1b/51.html"}},{"page_content":"The Project Gutenberg EBook of Moby-Dick; or The Whale, by Herman Melville\n\nThis eBook is for the use of anyone anywhere at no cost and with\r\nalmost no restrictions whatsoever.  You may copy it, give it away or\r\nre-use it under the terms of the Project Gutenberg License included\r\nwith this eBook or online at www.gutenberg.org\n\nTitle: Moby-Dick; or The Whale\n\nAuthor: Herman Melville\n\nLast Updated: January 3, 2009\n\nPosting Date: December 25, 2008 [EBook #2701]\n\nRelease Date: June, 2001\n\nLanguage: English","metadata":{"source":"/Users/rah/titleDownloads/2c169b4c-8e8d-4dd4-8b57-82d5a21e4a1b/fae7a981-6f18-423d-b8e1-a7b0c73101fc.html"}},{"page_content":"The Project Gutenberg EBook of Moby-Dick; or The Whale, by Herman Melville\n\nThis eBook is for the use of anyone anywhere at no cost and with\r\nalmost no restrictions whatsoever.  You may copy it, give it away or\r\nre-use it under the terms of the Project Gutenberg License included\r\nwith this eBook or online at www.gutenberg.org\n\nTitle: Moby-Dick; or The Whale\n\nAuthor: Herman Melville\n\nLast Updated: January 3, 2009\n\nPosting Date: December 25, 2008 [EBook #2701]\n\nRelease Date: June, 2001\n\nLanguage: English","metadata":{"source":"/Users/rah/titleDownloads/2c169b4c-8e8d-4dd4-8b57-82d5a21e4a1b/143.html"}}]}
```
So, no tokens are returned but the source documents are.  I've been debugging this for a while but haven't figured out a solution yet.

**Comment by auxon** [comment]
I think the problem might be that the llm_outputs is set to {} when the cache finds the prompt, but it's set when it doesn't:

![image](https://github.com/ajndkr/lanarky/assets/40005875/9c021039-6c51-44b2-beb2-c3c68a2b907f)

**Comment by auxon** [comment]
Note, my code is available in the Discussion here:  https://github.com/ajndkr/lanarky/discussions/108#discussion-5501534

**Comment by auxon** [comment]
I also tried using the in memory cache and got the same issue.

**Comment by auxon** [comment]
I'm guessing the issue is that AsyncIteratorCallbackHandler.on_llm_new_token is never invoked when the answer is retrieved from the cache; we need some way to add the retrieved text as either a token stream or to the final output.

**Comment by ajndkr** [comment]
hi @auxon, you are right. the `AsyncIteratorCallbackHandler.on_llm_new_token` method is not invoked because with caching we are not really making an LLM call. The callback handler needs to be updated to send the final output if caching is enabled. As you can see here: https://github.com/ajndkr/lanarky/blob/1bc1c1547c822bcfbe1149357b8be1aed56a7487/lanarky/callbacks/retrieval_qa.py#L84-L93

we don't send the final answer because the expectation is that the answer has already been streamed. Would you like to contribute towards this? Otherwise I'll push a fix in a couple of days.

**Comment by auxon** [comment]
Sure, I can contribute a fix, probably later tonight or tomorrow.
