### ISSUE TITLE
Feature Request: Customized Chain Support

### ISSUE THREAD

**Issue by ImanLakjiri** [ajndkr/lanarky#119]
**Description:**
I would like to propose a feature that allows users to customize existing chains, such as `RetrievalQAWithSourcesChain`, with slight modifications to their behavior. Currently, `LangchainRouter `supports specific `langchain_object` like `LLMChain`, `ConversationChain`, and more, but customizing these chains is limited.

**Use Case:**
For instance, I wanted to customize the `RetrievalQAWithSourcesChain` by overriding specific methods like `_split_sources` to adapt it to my project's requirements while retaining most of the original functionality.

**Proposed Solution:**
I suggest adding support for custom chains by allowing users to provide their custom chain classes that inherit from existing chain types, such as `RetrievalQAWithSourcesChain`. This would provide flexibility in using the library while maintaining compatibility with the core chain types.

**Example Usage:**
Here's how a customized chain could be implemented:

```
class CustomRetrievalQAWithSourcesChain(RetrievalQAWithSourcesChain):
    def _split_sources(self, answer: str) -> Tuple[str, str]:
        """Split sources from answer."""
        if re.search(r"SOURCES:\s", answer):
            answer, sources = re.split(r"SOURCES:\s|QUESTION:\s", answer)[:2]
            sources = ""  # Always return an empty string as the source
        else:
            sources = ""
        return answer, sources
```

**Request for FastAPI Example:**
Additionally, I kindly request an example of how to manually create an endpoint with FastAPI when using a customized chain. 

I believe this feature would make `lanarky` even more versatile and valuable to its users. Please consider implementing this enhancement.

Thank you for your attention to this feature request.

**Comment by ajndkr** [comment]
hi @ImanLakjiri!

Have you looked into https://lanarky.readthedocs.io/en/latest/langchain/custom_callbacks.html? You can register your own callbacks for a custom chain. Does this fit your requirement?

**Comment by ajndkr** [comment]
callback registry has been removed in v0.8 release.

Please view the new documentation on how you can pass custom callback handlers to `StreamingResponse` class here: https://lanarky.ajndkr.com/learn/adapters/langchain/fastapi/#streaming

**Comment by ajndkr** [comment]
please reopen this issue if you'd like to discuss more on this topic.
