### ISSUE TITLE
typing-extensions outdated for pydantic v2

### ISSUE THREAD

**Issue by Krupskis** [ajndkr/lanarky#123]
### Scenario
```
$ poetry add lanarky
```

### Actual result

```
Using version ^0.7.13 for lanarky

Updating dependencies
Resolving dependencies... (0.7s)

Because no versions of lanarky match >0.7.13,<0.8.0
 and lanarky (0.7.13) depends on typing-extensions (4.5.0), lanarky (>=0.7.13,<0.8.0) requires typing-extensions (4.5.0).
And because pydantic (2.3.0) depends on typing-extensions (>=4.6.1)
 and no versions of pydantic match >2.3.0,<3.0.0, lanarky (>=0.7.13,<0.8.0) is incompatible with pydantic (>=2.3.0,<3.0.0).
So, because core depends on both pydantic (^2.3.0) and lanarky (^0.7.13), version solving failed.
```
### Expected result
Lanarky successfully installed

**Comment by Krupskis** [comment]
From my research Pydantic v2 requires at least `4.6.1` version of `typing-extensions`

**Comment by ajndkr** [comment]
thanks for the raising the issue! @Krupskis 

would you like to contribute a fix towards this?

**Comment by Krupskis** [comment]
@ajndkr sure, opened #124

**Comment by ajndkr** [comment]
@Krupskis your changes will be available in `0.7.15`

**Comment by Krupskis** [comment]
@ajndkr sweet, how does it work with package updates? How long do they usually take?

**Comment by ajndkr** [comment]
i've already made a new release. the package should be available ~5-10 mins
