### ISSUE TITLE
Create Streaming for Agent types and add Memory

### ISSUE THREAD

**Issue by Sanjaypranav** [ajndkr/lanarky#127]
### Acceptance Criteria

- [ ]

**Comment by Sanjaypranav** [comment]
done

**Comment by ajndkr** [comment]
@Sanjaypranav please add more description for this feature request. it is always useful to mention what you want to achieve, what needs to be improved and possible solutions (if you have ideas). Also, please include some examples if possible.

**Comment by ajndkr** [comment]
closing due to insufficient description and user inactivity. 

please reopen this issue if you'd like to discuss this topic more.
