### ISSUE TITLE
How to custom an AsyncLanarkyCallback in llmchain?

### ISSUE THREAD

**Issue by nldxtd** [ajndkr/lanarky#138]
I need to write my response back to database as the llmchain ends. So I am trying to custom a handler like this:

```
class WriteResultAsyncHandler(AsyncLanarkyCallback):
    """Async callback handler that can be used to handle callbacks from langchain."""

    async def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        """Run when chain ends running."""
        ...
        
    def _construct_message(self, content: Any) -> Any:  # pragma: no cover
        """Constructs a Message from a string."""
        return content
```
the runtime error says: "'WriteResultAsyncHandler' object is not callable"
I tracked down the stack and find the callback is used in this way, which requires the callback to be callable:
```
def _create_chain_executor(
        chain: Chain,
        inputs: Union[dict[str, Any], Any],
        as_json: bool = False,
        callback: Optional[AsyncLanarkyCallback] = None,
        **callback_kwargs,
    ) -> Callable[[Send], Awaitable[Any]]:
        """Creates a function to execute ``chain.acall()``.

        ...

        async def wrapper(send: Send):
            return await chain.acall(
                inputs=inputs,
                callbacks=[callback(send=send, **callback_kwargs)],
            )

        return wrapper
```
But I have no idea how to make the customed callback object callable, can someone help me out?

**Comment by ajndkr** [comment]
hi! you can create `on_chain_end` or `on_agent_end` method based on your use case and add your db logic there. 

Alternatively, you can consider using `BackgroundTask` which is more fastapi-side solution. I can update the streaming response class to update the `kwargs` of `BackgroundTask` to add chain output.

**Comment by nldxtd** [comment]
Thank u for your quick response, does it mean if I change the on_llm_end function to on_agent_end, the "uncallable issue" will be solved?

The second solution seems good, but as I am new to FastAPI, I guess I would probably use the first method now. Thanks again for your patience!

**Comment by ajndkr** [comment]
> Thank u for your quick response, does it mean if I change the on_llm_end function to on_agent_end, the "uncallable issue" will be solved?

can't say for sure.. let's try it and see if it works.

**Comment by nldxtd** [comment]
I tried the first method, it didn't work though. So I am turning to the second method with background tasks.

But it seems lanarky.StreamingResponse does't work well with background tasks, cause I encountered the following problem:

```
self.background.kwargs["outputs"] = str(e)
    │    └ <starlette.background.BackgroundTasks object at 0x111a4bcd0>
    └ <lanarky.responses.streaming.StreamingResponse object at 0x1230fcd90>

AttributeError: 'BackgroundTasks' object has no attribute 'kwargs'
```
I think it's a wired problem because lanarky.StreamingResponse is a subclass of FastAPI.SreamingResponse
I think you may have thought about this before.

**Comment by nldxtd** [comment]
I think the problem is, I cannot add background tasks to lanarky.StreamingResponse

**Comment by ajndkr** [comment]
I see! I will add this feature soon then.
