### ISSUE TITLE
UserWarning: Field name "raise_error" shadows an attribute in parent "AsyncCallbackHandler";

### ISSUE THREAD

**Issue by PapuSwain25** [ajndkr/lanarky#141]
UserWarning: Field name "raise_error" shadows an attribute in parent "AsyncCallbackHandler";
UserWarning: Field name "run_inline" shadows an attribute in parent "AsyncCallbackHandler";
UserWarning: Field name "run_inline" shadows an attribute in parent "AsyncCallbackHandler";
UserWarning: Field name "run_inline" shadows an attribute in parent "AsyncLanarkyCallback"; 

Getting the above warning from pydantic\_internal\_fields.py:163. I'm using pydantic Version: 2.4.2.

Since, i'm new to Lanarky, unable to findout, what's the issue. Could anyone help me @ajndkr ?

**Comment by iangoodnight** [comment]
+1

**Comment by ajndkr** [comment]
Apologies for the delay… can you try downgrading pydantic to <2.0.0

i have no tested this library with pydantic 2.0+

**Comment by PapuSwain25** [comment]
For my use case, i need pydantic 2.0+. So, are you having any plan to test with pydantic 2.0+ @ajndkr ?

**Comment by ajndkr** [comment]
I see! I will test it with 2.0+ then. In the meantime, if you are able to find a fix, feel free to open a PR

**Comment by PapuSwain25** [comment]
Sure, thank you for your reply.

**Comment by ajndkr** [comment]
@PapuSwain25 i've bumped pydantic dependency in #149 but the changes will come into effect with v0.8 release. i have other features/bugfixes in mind. Will take a week or so until i make the new release.

**Comment by PapuSwain25** [comment]
@ajndkr Thank you...
