### ISSUE TITLE
Allow langchain version > 0.2.0 to be used

### ISSUE THREAD

**Issue by sarthaklangde** [ajndkr/lanarky#200]
**Description**
Currently in `pyproject.toml`, the version of `langchain` is set to be less than `0.2.0` but langchain is already at `0.2.5`. This creates dependency issues while using packages that require higher version of langchain.

**Code**
https://github.com/ajndkr/lanarky/blob/1a63b8707a9711c2bf819bdfca9d1ccccf8329a1/pyproject.toml#L23

**Comment by sarthaklangde** [comment]
@ajndkr would just bumping the version in `pyproject.toml` and running the tests in the repository ensure that nothing would break on release?

**Comment by ajndkr** [comment]
> @ajndkr would just bumping the version in `pyproject.toml` and running the tests in the repository be sufficient in ensuring that nothing would break on release?

I ran the example gradio apps with langchain>0.2 and they work fine.
