### ISSUE TITLE
Pass multiple Inputs to LLMChainStreamingResponse?

### ISSUE THREAD

**Issue by JulianKrmr** [ajndkr/lanarky#21]
I came across this library and I love it so far, I got the conversation chain running locally and would like to use it for my application now where I use my own LLMChain that I pass to LLMChainStreamingResponse.
My Problem is that I dont know how to pass my input keys to my prompt template when I use the from_chain method on LLMChainStreamingResponse. 

```
@app.post("/chat")
async def chat(request: Prompt) -> LLMChainStreamingResponse:
    context_str = get_context(request.prompt)
    return LLMChainStreamingResponse.from_chain(chain,
                                                inputs={"question": request.prompt, "context": context_str,
                                                        "history": ""},
                                                media_type="text/event-stream")
```

This is how I thought I could use it, 
I would be super thankful for advice!

**Comment by ajndkr** [comment]
Hi! nice to hear that!

it appears the recent changes don't allow for `inputs` to be a dictionary. I will make a PR to fix this soon.

**Comment by ajndkr** [comment]
@JulianKrmr i've pushed a fix for this issue. you can install the latest version of the library: `pip install fastapi-async-langchain==0.4.2`

let me know if it works for you now. cheers!

**Comment by JulianKrmr** [comment]
@ajndkr awesome! it is working now :) 
Thanks alot!
