### ISSUE TITLE
feat: setup project documentation

### ISSUE THREAD

**Issue by ajndkr** [ajndkr/lanarky#36]
As the project grows, there is a strong need for a docs page for new (and existing) users to find information which might be too verbose to add to the repo README.

For the first version, we can add:
- getting started
- api reference
- tutorial 1: deploy basic llm chain
- tutorial 2: deploy chains with vector store / retriever
- tutorial 3: deploy custom chains

### Acceptance Criteria

- [ ] study https://readthedocs.org/
- [ ] publish docs on https://readthedocs.org/

**Comment by ajndkr** [comment]
@rogalvil any recommendations towards this?

**Comment by rogalvil** [comment]
@ajndkr Honestly, I don't have any recommendations. I don't have much experience with documentation.
