### ISSUE TITLE
Streaming response returns 'StuffDocumentsChain' not the stream

### ISSUE THREAD

**Issue by gabriel-ecegi** [ajndkr/lanarky#46]
When calling StreamingResponse.from_chain, stream is not returned, instead 'StuffDocumentsChain' str is returned.

This code works as intended when calling normally without streaming. 
Motorhead memory was omitted to simplify code.

### Scenario

```
@app.get("/chat", response_model=ChatResponse)
async def chat_endpoint(
    sessionID: str, question: str, model: str, aimodel: str, engine: str
):
    chain, inputs = await answerQuestion(
        sessionID, question, model, aimodel
    )
    
    return StreamingResponse.from_chain(chain, inputs, media_type="text/event-stream")

async def answerQuestion(sessionID: str, question: str, model: str, ai_model: str):
    key = (
        os.environ.get("OPEN_API_KEY_GPT4")
        if ai_model == "gpt-4"
        else os.environ.get("OPEN_API_KEY")
    )

    namespace = "05a77398-8e25-49de-9ba1-3338366f2386"
    vectorstore = load_pinecone_existing_index(namespace, model)
    llm = OpenAI(
        openai_api_key=key,
        temperature=0.125,
        model_name=ai_model, 
        verbose=True, 
        streaming=True,
    )

    retriever = SelfQueryRetriever.from_llm(
        llm,
        vectorstore,
        document_content_description,
        metadata_field_info,
        verbose=True,
    )


    template = """Some template...

    {context}

    {chat_history}
    Zákazník: {human_input}
    Chatbot:"""

    docs = retriever.get_relevant_documents(question)

    llm = ChatOpenAI(
        model_name=ai_model,
        streaming=True,
        verbose=True,
        temperature=0.125,
        max_tokens=600,
        openai_api_key=key,
    )

    prompt = PromptTemplate(
        input_variables=["chat_history", "human_input", "context"], template=template
    )

    chain = load_qa_chain(
        llm=llm,
        document_variable_name="context",
        chain_type="stuff",
        prompt=prompt,
        verbose=True,
    )

    inputs = {
        "input_documents": docs,
        "human_input": question,
    }

    return chain, inputs

```

### Actual result

 'StuffDocumentsChain' 

![image](https://github.com/ajndkr/lanarky/assets/35489017/df0f3ce7-38ec-405b-ae9c-377b81cbfd4d)

### Expected result

Stream is returned. For example case, from Read.me it works

### Acceptance criteria

Endoint should return stream.

**Comment by ajndkr** [comment]
@gabriel-ecegi ah! i understand the problem here. this particular chain type is not yet supported and throws a KeyError which gets streamed. There's an issue related to this: https://github.com/ajndkr/lanarky/issues/35. I plan on adding a docs page for this project ASAP.

In the meantime, I will improve the error message as the above is indeed very confusing.

**Comment by gabriel-ecegi** [comment]
Thank you, I will be looking forward to this feature. 

So if I understand correctly, I can make it work by adding

`@register_streaming_callback("StuffDocumentsChain")
class AsyncStuffDocumentsChainStreamingCallback(AsyncStreamingResponseCallback):
    """AsyncStreamingResponseCallback handler for StuffDocumentsChain."""

    pass
`

I have added it, now it does not throw any arror, but also does not return anything.

**Comment by ajndkr** [comment]
yup! but it looks like the callback doesn't work for `StuffDocumentsChain`. can you try by inheriting `AsyncBaseRetrievalQAStreamingCallback` instead of `AsyncStreamingResponseCallback`? 

you can do the following:

```
from lanarky.callbacks import AsyncRetrievalQAStreamingCallback

@register_streaming_callback("StuffDocumentsChain")
class AsyncStuffDocumentsChainStreamingCallback(AsyncStreamingResponseCallback):
    """AsyncStreamingResponseCallback handler for StuffDocumentsChain."""

    pass
```

let me know if it works!

**Comment by gabriel-ecegi** [comment]
Thank you, it works now.
