### ISSUE TITLE
ERROR - Async generation not implemented for this LLM.

### ISSUE THREAD

**Issue by pakcheera** [ajndkr/lanarky#49]
​I use the example file "retrieval_qa_w_sources.py" but change the LLM model to GPT4All but It got error that

`ERROR - Async generation not implemented for this LLM`

Is it not support for that LLM or how I solve it?

**Comment by ajndkr** [comment]
Hi! I believe it’s a Langchain issue. Since this package uses async methods, likely the `agenerate` method of the gpt4all llm wrapper is not implemented and hence throws this error.

**Comment by marcovirgolin** [comment]
I encountered this before and can confirm

**Comment by ajndkr** [comment]
@pakcheera i suggest adding the `async` methods first and then trying again.

**Comment by ajndkr** [comment]
@pakcheera will be closing this for now as there's nothing to do from lanarky end.

**Comment by ibivibiv** [comment]
Honestly if you want to just call a synchronous call into langchain if the model you've selected doesn't do async you can just change out the behavior in "lanarky/routing/utils" at line 153 to not call "acall" and instead do this:

`return langchain_object.__call__(
            inputs=request.dict(), return_only_outputs=True
        )`

Its a hack but it works.
