### ISSUE TITLE
Metadata returned in docs

### ISSUE THREAD

**Issue by audvin** [ajndkr/lanarky#50]
How should one go about extracting and outputting more doc meta data than just "source"? 
In my Pinecone vector db, I have entered additional meta data like "author" etc.

**Comment by ajndkr** [comment]
Hi! @audvin 

for the time being, you can create a new callback handler which inherits from `AsyncBaseRetrievalQAStreamingCallback`. You will need to then update the `on_chain_end` method logic.

https://github.com/ajndkr/lanarky/blob/9c3e0a40f2877bc7878901d92c73aee00f0cc230/lanarky/callbacks/retrieval_qa.py#L13-L28

You will need to register this callback. You can follow the docs for this: https://lanarky.readthedocs.io/en/latest/advanced/custom_callbacks.html

In the meantime, I will keep this issue open to integrate this feature in the library.

**Comment by audvin** [comment]
I seem to be stuck using this with the conversational_retrieval.py example. 

Getting this error: 
`NameError: name 'CallbackManagerForChainRun' is not defined`

**Comment by ajndkr** [comment]
@audvin can you please share your full code?

**Comment by audvin** [comment]
qa_with_sources.py, I put this at the bottom:

```
@register_streaming_callback("ConversationalRetrievalWithSourcesChain")
class AsyncConversationalRetrievalWithSourcesChainStreamingCallback(
    AsyncConversationalRetrievalChainStreamingCallback
):
    """AsyncStreamingResponseCallback handler for ConversationalRetrievalWithSourcesChain."""
    pass
```

in conversational_retrieval.py, I put this:

```
class ConversationalRetrievalWithSourcesChain(ConversationalRetrievalChain):
    """Chain for chatting with sources over documents."""

    sources_output_key: str = "sources"  #: :meta private:

    @property
    def output_keys(self) -> List[str]:
        """Return the output keys.

        :meta private:
        """
        _output_keys = [self.output_key]
        _output_keys.append(self.sources_output_key)
        if self.return_source_documents:
            _output_keys = _output_keys + ["source_documents"]
        return _output_keys

    def _call(
        self,
        inputs: Dict[str, Any],
        run_manager: Optional[CallbackManagerForChainRun] = None,
    ) -> Dict[str, Any]:
        result = super()._call(
            inputs=inputs,
            run_manager=run_manager,
        )
        answer = result[self.output_key]
        if re.search(r"SOURCES:\s", answer):
            answer, sources = re.split(r"SOURCES:\s", answer)
        else:
            sources = ""
        result[self.output_key] = answer
        result[self.sources_output_key] = sources
        return result

    async def _acall(
        self,
        inputs: Dict[str, Any],
        run_manager: Optional[AsyncCallbackManagerForChainRun] = None,
    ) -> Dict[str, Any]:
        result = await super()._acall(
            inputs=inputs,
            run_manager=run_manager,
        )
        answer = result[self.output_key]
        if re.search(r"SOURCES:\s", answer):
            answer, sources = re.split(r"SOURCES:\s", answer)
        else:
            sources = ""
        result[self.output_key] = answer
        result[self.sources_output_key] = sources
        return result
```

**Comment by ajndkr** [comment]
Thanks. Will look into this soon.

**Comment by ajndkr** [comment]
@audvin I think you just need to fix the missing imports. can you add the following import statement and try again?

```
from langchain.callbacks.manager import (
    AsyncCallbackManagerForChainRun,
    CallbackManagerForChainRun,
)
```

I will fix the docs to make this explicit.

**Comment by audvin** [comment]
Thank you, I added those and that got me further but I can't seem to effect the outputs, and I'm getting this error while chatting: 

```
> Entering new ConversationalRetrievalChain chain...
Error in on_llm callback: 'AsyncConversationalRetrievalChainStreamingCallback' object has no attribute 'on_llm'
Error in on_llm callback: 'AsyncConversationalRetrievalChainStreamingCallback' object has no attribute 'on_llm'
```

**Comment by ajndkr** [comment]
right! you need to upgrade the langchain version. this was a bug introduced inside langchain a few versions back. I suggest installing: `pip install langchain==0.0.175`

**Comment by ajndkr** [comment]
@audvin hi! i've updated the retrieval qa callback handler in `0.6.5` to stream all document metadata and not just `source`. 

It should be available soon.

```
pip install lanarky==0.6.5
```

let me know if it helps! feel free to open new issues for any improvements or bug fixes. cheers!
