### ISSUE TITLE
It is difficult to determine the output result when I use requests to call the API.

### ISSUE THREAD

**Issue by gaye746560359** [ajndkr/lanarky#62]
params = {
    "query": "What is Google for?"
}
for resp in requests.post(url="http://127.0.0.1:8000/sseAsk", json=params, stream=True).iter_content(
        chunk_size=None, decode_unicode=False):
    print(str(resp, 'utf8'))

The returned results are as follows:
{"token":""}
{"token":"Google"}
...
{"token":"。"}
{"token":""}
{"token":"","source_documents":...}

How should I determine the timing of the appearance of source_documents?

**Comment by ajndkr** [comment]
@gaye746560359 you can check the following example and update your code accordingly:

- run retrieva qa demo: `uvicorn app.retrieval_qa_w_sources:app --reload`
- add the following code to `test_client.py`:

```
import json
import requests

query = "Give me list of text splitters available with code samples"
api_url = "http://localhost:8000/chat_json"
payload = {"query": query}
headers = {
    "accept": "text/event-stream",
    "Content-Type": "application/json",
    "Connection": "keep-alive",
}

try:
    response = requests.post(
        api_url, headers=headers, json=payload, timeout=60, stream=True
    )
    response.raise_for_status()  # Raise stored HTTPError, if one occurred

except requests.exceptions.HTTPError as httpErr:
    print(f"HTTP error occurred: {httpErr}")
except requests.exceptions.ConnectionError as connErr:
    print(f"Error connecting: {connErr}")
except requests.exceptions.Timeout as timeOutErr:
    print(f"Timeout error: {timeOutErr}")
except requests.exceptions.RequestException as reqErr:
    print(f"Something went wrong with the request: {reqErr}")

for chunk in response.iter_content(chunk_size=None):  # Smaller chunk size
    if chunk:
        data = json.loads(chunk.decode())
        token = data.get("token")
        source_documents = data.get("source_documents")
        if token:
            print(f"token: {token}")
        if source_documents:
            print(f"source_documents: {source_documents}")
```

- run `test_client.py`

**Comment by gaye746560359** [comment]
> @gaye746560359 you can check the following example and update your code accordingly:
> 
> * run retrieva qa demo: `uvicorn app.retrieval_qa_w_sources:app --reload`
> * add the following code to `test_client.py`:
> 
> ```
> import json
> import requests
> 
> query = "Give me list of text splitters available with code samples"
> api_url = "http://localhost:8000/chat_json"
> payload = {"query": query}
> headers = {
>     "accept": "text/event-stream",
>     "Content-Type": "application/json",
>     "Connection": "keep-alive",
> }
> 
> try:
>     response = requests.post(
>         api_url, headers=headers, json=payload, timeout=60, stream=True
>     )
>     response.raise_for_status()  # Raise stored HTTPError, if one occurred
> 
> except requests.exceptions.HTTPError as httpErr:
>     print(f"HTTP error occurred: {httpErr}")
> except requests.exceptions.ConnectionError as connErr:
>     print(f"Error connecting: {connErr}")
> except requests.exceptions.Timeout as timeOutErr:
>     print(f"Timeout error: {timeOutErr}")
> except requests.exceptions.RequestException as reqErr:
>     print(f"Something went wrong with the request: {reqErr}")
> 
> for chunk in response.iter_content(chunk_size=None):
>     if chunk:
>         data = json.loads(chunk.decode())
>         token = data.get("token")
>         source_documents = data.get("source_documents")
>         if token:
>             print(f"token: {token}")
>         if source_documents:
>             print(f"source_documents: {source_documents}")
> ```
> 
> * run `test_client.py`

Thank you! He is an effective worker.

**Comment by ajndkr** [comment]
great! closing issue for now.
