### ISSUE TITLE
Add documentation for using Feat: JSON RESPONSE

### ISSUE THREAD

**Issue by Haste171** [ajndkr/lanarky#63]
Please add documentation for using JSON RESPONSE feature for streaming responses..

**Comment by ajndkr** [comment]
@Haste171 sure! will update the docs over the weekend. In the meantime, you can check out one of the demo examples:

https://github.com/ajndkr/lanarky/blob/6e24c1d2f85ab4606f952974e181962e144ddaa7/examples/app/conversation_chain.py#L52-L59

The usage is very simple. You use the same `StreamingResponse` class but pass `as_json=True` to stream content as JSON.

**Comment by Haste171** [comment]
It doesn't exist?

**Comment by Haste171** [comment]
No, I updated to .6 (same thing it says on github)

**Comment by ajndkr** [comment]
Hmm.. that is odd. Can you please share the full traceback error log?

**Comment by ajndkr** [comment]
@Haste171 i've introduced a new feature. You can check the docs for usage: https://lanarky.readthedocs.io/en/latest/langchain/deploy.html

Covers documentation for JSON streaming response as well. Closing issue for now.
