### ISSUE TITLE
When will support for GPTCache or RedisSemanticCache be added?

### ISSUE THREAD

**Issue by gaye746560359** [ajndkr/lanarky#67]
When will support for GPTCache or RedisSemanticCache be added?
This is very important in local knowledge application.

**Comment by ajndkr** [comment]
Hi! Currently, it’s just me building this library. So progress is a bit slow. If you’d like to contribute, we can discuss implementation solution here. 

I recently added added a feature called `LangchainRouter` which I believe will allow me to add features like gptcache more easily as lifespan events. 

Nevertheless, I can prioritise this feature to implement.

**Comment by ajndkr** [comment]
I haven’t heard of RedisSemanticCache. Can you send me the link to this?

**Comment by gaye746560359** [comment]
> 我还没有听说过 RedisSemanticCache。你能把这个链接发给我吗？

https://python.langchain.com/en/latest/modules/models/llms/examples/llm_caching.html?highlight=RedisSemanticCache#semantic-cache
![image](https://github.com/ajndkr/lanarky/assets/3060035/f5116186-ed12-4225-b61f-0ac271971b97)

**Comment by gaye746560359** [comment]
> 你好！目前，只有我在构建这个库。所以进度有点慢。如果您想做出贡献，我们可以在这里讨论实施解决方案。
> 
> 我最近添加了一个功能`LangchainRouter`，我相信它可以让我更容易地添加像 gptcache 这样的功能作为生命周期事件。
> 
> 不过，我可以优先实现此功能。

Sorry, my current coding level is not sufficient to support it.

**Comment by ajndkr** [comment]
No problem. This will be the next feature I work on.

**Comment by SimFG** [comment]
@ajndkr  reference: https://python.langchain.com/en/latest/modules/models/llms/examples/llm_caching.html#gptcache
if you encounter any problem about the GPTCache usage, please feel free to give me a issue.

**Comment by ajndkr** [comment]
@gaye746560359 I've added the llm caching feature. You can find the usage docs here: https://lanarky.readthedocs.io/en/latest/langchain/cache.html

let me know if this works for your use case!

**Comment by ajndkr** [comment]
> @ajndkr reference: https://python.langchain.com/en/latest/modules/models/llms/examples/llm_caching.html#gptcache if you encounter any problem about the GPTCache usage, please feel free to give me a issue.

@SimFG whoops! missed your message! didn't encounter any issues.

**Comment by gaye746560359** [comment]
> @gaye746560359我添加了 llm 缓存功能。你可以在这里找到使用文档：https://lanarky.readthedocs.io/en/latest/langchain/cache.html
> 
> 让我知道这是否适用于您的用例！

我注意到v0.7.3版本中的LangchainRouter。但对于我现有的代码如何重构？
`
app = FastAPI()
embeddings = OpenAIEmbeddings()

langchain.llm_cache = RedisSemanticCache(
    redis_url="redis://127.0.0.1:7777",
    embedding=embeddings
)

v_db = Milvus(
    embeddings,
    connection_args={"host": "127.0.0.1", "port": "19530"},
    collection_name="LangChainCollection",
)

class Ask(BaseModel):
    query: Optional[str] = None

@app.post("/sseAsk")
async def sseask(ask: Ask):
    llm = ChatOpenAI(
        max_tokens=1000,
        temperature=0,
        model_name="gpt-3.5-turbo",
        streaming=True)

    system_template = """Given the following extracted parts of a long document and a question, create a final answer with references ("SOURCES"). 
                        If you don't know the answer, just say that it was not found in the knowledge base. Do not attempt to fabricate an answer.
                        ALWAYS return a "SOURCES" part in your answer.
                        Respond in Chinese.

                        QUESTION: {question}
                        =========
                        {summaries}
                        =========
                        FINAL ANSWER IN Chinese:"""

    messages = [
        SystemMessagePromptTemplate.from_template(system_template),
        HumanMessagePromptTemplate.from_template('{question}')
    ]

    prompt = ChatPromptTemplate.from_messages(messages)

    qa_chain = RetrievalQAWithSourcesChain.from_chain_type(
        llm=llm,
        chain_type_kwargs={"prompt": prompt},
        chain_type="stuff",
        retriever=v_db.as_retriever(),
        return_source_documents=True,
    )
    return StreamingResponse.from_chain(qa_chain, ask.query, as_json=True, media_type="text/event-stream")
`

langchain_router = LangchainRouter(
    langchain_url="/sseAsk",
    langchain_object=LLMChain.from_string(
        llm=OpenAI(temperature=0), template="Answer the query.\n{query}"
    ),
    streaming_mode=0,
)

app.include_router(langchain_router)
