### ISSUE TITLE
feat: Allow overriding registered callbacks

### ISSUE THREAD

**Issue by rbbby** [ajndkr/lanarky#74]
I have created a custom streaming callback and am trying to register it with `@register_streaming_callback("AgentExecutor")` but it raises `KeyError: "<class 'app.callbacks.MyCustomAgentsStreamingCallback'> already registered as AgentExecutor"`.

It would be very convenient to be able to override the default lanarky `AgentExecutor` callback since otherwise I have to create a custom `AgentExecutor`, register it and then write more code that supports my custom agent (for example the `initialize_agent` function in langchain which does not support custom agents atm. The workaround is further not ideal since I may not need a custom `AgentExecutor`, but only a custom callback handler.

One simple solution would be to simply replace the `raise` with a warning here instead https://github.com/ajndkr/lanarky/blob/main/lanarky/register/base.py#L26.

### Acceptance Criteria

- [ ] Being able to override registered callbacks

**Comment by ajndkr** [comment]
That’s a good point! I will add a feature to override existing callbacks

**Comment by ajndkr** [comment]
@rbbby the feature has been added. please install the latest version (`0.7.4`). You can use the `override` param:

```
from lanarky.register import register_streaming_callback

@register_streaming_callback("AgentExecutor", override=True)
class MyCustomAgentsStreamingCallback:
 ...
```

let me know if you face any issues!
