### ISSUE TITLE
feat: do we can handler multiple conversation, like `new chat` button in https://chat.openai.com/

### ISSUE THREAD

**Issue by KevinZhang19870314** [ajndkr/lanarky#87]
do we can handler multiple conversation, like `new chat` in https://chat.openai.com/

**Comment by ajndkr** [comment]
Hi @KevinZhang19870314 ! handling multiple conversations is a frontend task. 

I recently collaborated with menlolabs to integrate chatbot-ui with lanarky. you can find the repo here: https://github.com/menloparklab/chatbot-ui

**Comment by KevinZhang19870314** [comment]
Ok, I'll check that and let you know if it works, thank you for your response!

**Comment by ajndkr** [comment]
great! I will be closing the issue for now.
