### ISSUE TITLE
More complete explanation to get started

### ISSUE THREAD

**Issue by lchoquel** [ajndkr/lanarky#93]
Thank you for this great initiative.

It would be nice to have more complete examples to get started.
The inclusion of a testing gradio UI is great news but in order to get it to work there needs more stuff than what you provide in this quick-start code:

```
langchain_router = LangchainRouter(
    langchain_url="/chat",
    langchain_object=ConversationChain(
        llm=ChatOpenAI(temperature=0), verbose=True
    ),
    streaming_mode=1
  )
app.include_router(langchain_router)
```

I figured I could get the gradio interface to work using `testing.gradio.mount_gradio_app(app=app)` but that's not perfect because the gradio chat displays the answer as json code instead of text.
Also I'm still struggling to get the streaming to work on gradio. Something else is missing it fails and I get this error: "Error in on_chain_start callback: 'name'"). I guess a callback is missing?

Thanks for your help.

**Comment by lchoquel** [comment]
Allright so right after I posted I found I was missing the streaming=True param for ChatOpenAI(), which fixes the json/text issue and the streaming issue, nevermind.
So in the end what's missing from is just the line to attach gradio.

**Comment by ajndkr** [comment]
You make a good point. documentation definitely needs more work. Also, I will find a better way to mount the gradio app than `testing.gradio.mount_gradio_app(app=app)`. it's not a very fastapi-way to do things. I will update docs accordingly. 

In the meantime, if you have any questions, please ask them here and I will respond asap. I can then use this issue as an outline to update the docs

**Comment by ajndkr** [comment]
please check the new documentation on getting started: https://lanarky.ajndkr.com/getting-started/

note: i have removed gradio integration because it's a sub-optimal solution. I will rethink this feature and plan next steps accordingly.

please reopen this issue if you'd like to discuss more.
